name: Deploy to ECS

on:
  push:
    branches: [master] 

env:
  AWS_REGION: us-east-2
  ECR_REPO: project-repo
  ECS_CLUSTER: ecs-cluster
  ECS_SERVICE: ecs-service
  TASK_DEF: ecs-task-def.json
  CONTAINER_NAME: ecs-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
   

   
    - name: Deploy to ECS
      run: |
        aws ecs register-task-definition \
          --cli-input-json file://ecs-task-def.json

        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment

